### ISSUE TITLE
Success typing and other approaches?

### ISSUE THREAD

**Issue by JoeOsborn** [samth/gradual-typing-bib#2]
I guess this is a "related" approach, but it answers a distinct question: "if I run this program, is it guaranteed to exhibit a runtime error?" For languages like Erlang, where any ill-typed calls to standard functions or any unmatchable terms will raise exceptions, this is quite handy in practice, and it never rejects a sound program (though it might accept unsound ones), which is a good fit for gradual typing.

Manual type annotations can also be provided and checked against inferred annotations.

A [paper](http://www.it.uu.se/research/group/hipe/papers/succ_types.pdf) and an [LTU thread](http://lambda-the-ultimate.org/node/1910).

**Comment by vendethiel** [comment]
> Success typing isn't gradual typing; it doesn't say anything about safe interoperation, which is the core issue in gradual typing.

Would you care to explain that a bit more? (isn't success typing saying basically "whatever we can't infer has bottom type"?)

**Comment by bennn** [comment]
Success typing is trying to find code that will _definitely_ type error at compile-time. If the code might error, but might work alright, the type checker doesn't raise an alarm. And that's it.

Gradual typing does static checking and adds run-time type enforcement. That's what Sam means by safe interoperation.

So if a function `f` has the type `Natural -> Natural` then calls like `f "hello"` and `f -1` are all flagged as type errors before any code inside `f` is run.
When the calls are made from typed code, the type error happens at compile-time. When the calls are made from untyped code, the type error happens at runtime -- but you definitely get an error. Whereas success typing only gives an error if the body of `f` happens to raise an error.

**Comment by vendethiel** [comment]
Ah; okay. Thanks!
